### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Crypto2legit** [ScavengerBot/ScavengerBot#3]
Please provide any enhancements or updates you would like to see.

**Comment by smoochy** [comment]
- Notifications for sold positions. How many positions sold, which Profit. How long it took to accumulate those positions (time since last sale). Name of the Bitmex account the notification is coming from. Not sure if it is necessary to push Ever purchase of a position though. Notifications could be done through a Telegram or discord Bot. Maybe also the possibility to get account details through that Bot. Like current available balance, total balance etc. 

- statistics like PTTracker. People love looking at charts and see their amount of BTC growing. That keeps them motivated. I know you Already have planned something like this. 

- renaming of Bots on the website. 

- a wiki (in different languages perhaps) which describes the streamlined process from first accessing the SB website to the point the Bot is trading. In easily understandable steps. Maybe supported by YouTube videos.

**Comment by weyandch** [comment]
-  more stats on the current position a bot is working with, current position size, calculated order size the bot is using.

- possibility to switch long/short mode on a runnning bot. once he sold his batch, he'll switch direction

- prepaid mechanism (should discount on fees) to avoid weekly/bi-weekly transfer of provison fees

**Comment by Crypto2legit** [comment]
> * Notifications for sold positions. How many positions sold, which Profit. How long it took to accumulate those positions (time since last sale). Name of the Bitmex account the notification is coming from. Not sure if it is necessary to push Ever purchase of a position though. Notifications could be done through a Telegram or discord Bot. Maybe also the possibility to get account details through that Bot. Like current available balance, total balance etc.
> * statistics like PTTracker. People love looking at charts and see their amount of BTC growing. That keeps them motivated. I know you Already have planned something like this.
> * renaming of Bots on the website.
> * a wiki (in different languages perhaps) which describes the streamlined process from first accessing the SB website to the point the Bot is trading. In easily understandable steps. Maybe supported by YouTube videos.

We are will be releasing a tracker shortly it is on the roadmap. We will look into having the ability for changing bot names. Are there any specific languages you are considering should be on here specifically?

**Comment by Crypto2legit** [comment]
> * more stats on the current position a bot is working with, current position size, calculated order size the bot is using.
> * possibility to switch long/short mode on a runnning bot. once he sold his batch, he'll switch direction
> * prepaid mechanism (should discount on fees) to avoid weekly/bi-weekly transfer of provison fees

The first request can be resolved by having 2 accounts but we will look into this option further which we have spoken about. You can expect in the near future for many UI data options including tracking and notifications. We are working on a prepaid version to avoid fee's currently and will announce when ready. Thank you for providing your recommendations. This is a community driven software!

**Comment by smoochy** [comment]
> Are there any specific languages you are considering should be on here specifically?

English of course and maybe German? At least those are the ones I could help with.

**Comment by weyandch** [comment]
The bot shoudl place a stoploss order close to the current liquidation price. 
Bitmex liquidation fees are outrageous, thus you safe lots of money in case the strategy fails and one gets liquidated.

**Comment by smoochy** [comment]
- If the time for a funding on the LONG Bot is coming, and the Bot is in positive profit, sell, no matter what. 
If the Bot is in negative Profit, calculate if it is less loss to pay funding or SL and do this.

**Comment by Crypto2legit** [comment]
It may be an option down the line as another option. Take a look at he results channel and you will see that it doesnt take away from being profitable. Look up how being a market maker works via the discord by typing in !market

**Comment by tes724** [comment]
When funding's turns from longs to short or other way around. I would love to see it switch direction after next sell off. This way we can always get the funding to our advantage.

**Comment by Crypto2legit** [comment]
> When funding's turns from longs to short or other way around. I would love to see it switch direction after next sell off. This way we can always get the funding to our advantage.

This is a strategy we have in the works and in testing. Stay tuned for any announcements regarding this!

**Comment by Crypto2legit** [comment]
> * If the time for a funding on the LONG Bot is coming, and the Bot is in positive profit, sell, no matter what.
>   If the Bot is in negative Profit, calculate if it is less loss to pay funding or SL and do this.

This is being worked on currently thank you for the input.

**Comment by jadiesel** [comment]
Would love to have a 'soft stop'... Tell the bot to stop after it exits the current position. Basically - No new positions please.

Maybe some notifications on position closes too.... since that goes hand in hand...

**Comment by CryptoChronologist** [comment]
How is it that this platform still only support BitMex as it's trading platform? There are other exchanges that leverage trading and API key creation is possible on like ByBit. I remember it was promised by the developer(s) that other exchanges would be added over a year ago and this never happen. Who wants to continue to use BitMex with all their flaws...

**Comment by bigcountry-scav** [comment]
@CryptoChronologist these releases are actually leading up to releases of Bybit/Deribit/Binance/Kraken/FTX to name a few.

**Comment by CryptoChronologist** [comment]
It's good to know this project isn't dead (**I think**) and I haven't used your platform because I don't use BitMex and haven't in over a year. Who wants to deal with the crap that BitMex puts you through. Now they are in trouble with the US and moving thousand of Bitcoins off the platform. Hmmmm; can you spot a sinking ship...
You guys need to get with the program and get the platform working on those other exchanges ASAP. It has been a long time since the addition other exchanges has been promised and I cannot believe that not even one has been added.
